name: datasist-env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2019.11.27=0
  - certifi=2019.11.28=py37_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.1=he6710b0_1
  - openssl=1.1.1d=h7b6447c_3
  - pip=19.3.1=py37_0
  - python=3.7.5=h0371630_0
  - readline=7.0=h7b6447c_5
  - setuptools=44.0.0=py37_0
  - sqlite=3.30.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.33.6=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - alabaster==0.7.12
    - attrs==19.3.0
    - babel==2.8.0
    - backcall==0.1.0
    - bleach==3.1.0
    - chardet==3.0.4
    - cycler==0.10.0
    - decorator==4.4.1
    - defusedxml==0.6.0
    - docutils==0.15.2
    - entrypoints==0.3
    - idna==2.8
    - imagesize==1.2.0
    - importlib-metadata==1.3.0
    - ipykernel==5.1.3
    - ipython==7.11.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.15.2
    - jinja2==2.10.3
    - joblib==0.14.1
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==5.3.4
    - jupyter-console==6.0.0
    - jupyter-core==4.6.1
    - kiwisolver==1.1.0
    - markupsafe==1.1.1
    - matplotlib==3.1.2
    - mistune==0.8.4
    - more-itertools==8.0.2
    - nbconvert==5.6.1
    - nbformat==5.0.3
    - notebook==6.0.2
    - numpy==1.18.1
    - packaging==20.0
    - pandas==0.25.3
    - pandocfilters==1.4.2
    - parso==0.5.2
    - pexpect==4.7.0
    - pickleshare==0.7.5
    - prometheus-client==0.7.1
    - prompt-toolkit==2.0.10
    - ptyprocess==0.6.0
    - pygments==2.5.2
    - pyparsing==2.4.6
    - pyrsistent==0.15.6
    - python-dateutil==2.8.1
    - pytz==2019.3
    - pyzmq==18.1.1
    - qtconsole==4.6.0
    - requests==2.22.0
    - scikit-learn==0.22.1
    - scipy==1.4.1
    - seaborn==0.9.0
    - send2trash==1.5.0
    - six==1.13.0
    - snowballstemmer==2.0.0
    - sphinx==2.3.1
    - sphinxcontrib-applehelp==1.0.1
    - sphinxcontrib-devhelp==1.0.1
    - sphinxcontrib-htmlhelp==1.0.2
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.2
    - sphinxcontrib-serializinghtml==1.1.3
    - terminado==0.8.3
    - testpath==0.4.4
    - tornado==6.0.3
    - traitlets==4.3.3
    - urllib3==1.25.7
    - wcwidth==0.1.8
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
    - zipp==0.6.0
prefix: /home/risingodegua/anaconda3/envs/datasist-env

